name: health-cloud

services:
  - type: web
    buildCommand: "pip install -r requirements.txt"
    installCommand: "pip install -r requirements.txt"
    runCommand: "gunicorn app:app -b 0.0.0.0:$PORT"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      SECRET_KEY: supersecretkey
    ports:
      - name: http
        port: 8080
        protocol: http
